server:
  port: ${SERVER_PORT:8080}
spring:
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    protocol: ${SPRING_MAIL_PROTOCOL:smtp}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:""}
    password: ${SPRING_MAIL_PASSWORD:""}
    properties:
      mail:
        smtp:
          auth: ${SPRING_EMAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_EMAIL_SMTP_TTL_ENABLE:true}
